apiVersion: v1
kind: Service
metadata:
  name: {{ include "sports-betting.fullname" . }}-api
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: api
    {{- include "sports-betting.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.api.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/component: api
    {{- include "sports-betting.selectorLabels" . | nindent 4 }}
