[project]
name = "accuribet-service"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "aiohttp>=3.13.5",
    "fastapi>=0.135.3",
    "fastapi-utils>=0.8.0",
    "pydantic-settings>=2.13.1",
]

[build-system]
requires = ["uv_build>=0.11.3,<0.12"]
build-backend = "uv_build"

