name: Build and Test Solid.js Project

on:
  push:
    paths:
      - '**.js'
      - '**.json'
      - '**.lock'
      - '**.md'
      - '**.ts'
      - '**.yml'
      - '.github/workflows/website.yml'
      - 'Website/Dockerfile'
      - 'package.json'
      - '**.json'
    branches: [ main, ci-test ]
  pull_request:
    paths:
      - '**.js'
      - '**.json'
      - '**.lock'
      - '**.md'
      - '**.ts'
      - '**.yml'
      - '.github/workflows/website.yml'
      - 'Dockerfile'
      - 'package.json'
      - '**.json'
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 19.2
      - run: npm install
        working-directory: ./Website
      - run: npm run build
        working-directory: ./Website

